function[ o ] = generate_hexa_connectivity( im )

% Defines a Connectivity matrix from an image ( 3 x Nx x Ny x Nz )

Nx = size(im,2); Ny = size(im,3); Nz = size(im,4);

if rem(Nx,2) == 0 
  Nx = Nx - 1;
end

if rem(Ny,2) == 0 
  Ny = Ny - 1;
end

if rem(Nz,2) == 0
  Nz = Nz - 1;
end
Ex = (Nx - 1)/2; Ey = (Ny - 1)/2; Ez = (Nz - 1)/2;  
E = Ex * Ey * Ez;
o = zeros(E, 27);
n = 1;
c = 1;
fn = 1; 

for k = 1:Ez
  for j = 1:Ey
    for i = 1:Ex
      if i == 1
        sn = n;
      end
      o(c,:) = [...
        n               ,...
        n+2             ,...
        n+2*Nx          ,...
        n+2+2*Nx        ,...
        n+2*Nx*Ny       ,...
        n+2+2*Nx*Ny     ,...
        n+2*Nx+2*Nx*Ny  ,...
        n+2+2*Nx+2*Nx*Ny,...
        n+1             ,...
        n+Nx            ,...
        n+1+Nx          ,...
        n+2+Nx          ,...
        n+1+2*Nx        ,...
        n+Nx*Ny         ,...
        n+1+Nx*Ny       ,...
        n+2+Nx*Ny       ,...
        n+Nx+Nx*Ny      ,...
        n+1+Nx+Nx*Ny    ,...
        n+2+Nx+Nx*Ny    ,...
        n+2*Nx+Nx*Ny    ,...
        n+1+2*Nx+Nx*Ny  ,...
        n+2+2*Nx+Nx*Ny  ,...
        n+1+2*Nx*Ny     ,...
        n+Nx+2*Nx*Ny    ,...
        n+1+Nx+2*Nx*Ny  ,...
        n+2+Nx+2*Nx*Ny  ,...
        n+1+2*Nx+2*Nx*Ny];
      c = c + 1;
      n = n + 2;
    end
    n = sn + 2*Nx;  
  end
  n = fn + 2*Nx*Ny; 
  fn = fn + 2*Nx*Ny;
end